# This workflow will install Python dependencies and run a Python script.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GetBenzaPricesPython application

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *"    #runs at 11:30 UTC everyday
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

#permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        #pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Exec script
      run: |
        python GetBenzaPrices.py
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated on ${timestamp}" || exit 0
        git push
    - name: Push directory to another repository directory
      uses: XenonMolecule/github-action-push-to-another-repository@0.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'output'
        destination-github-username: 'IlBano'
        destination-repository-name: 'ilbano.github.io'
        user-email: a-obani@gmail.com
        target-branch: main
      
